### ISSUE TITLE
Does discourse_cas_sso trust all email addresses or require validation?

### ISSUE THREAD

**Issue by sudoman** [eriko/discourse_cas_sso#10]
Hello eriko,

I'm still setting up discourse_cas_sso and was wondering whether this module validates email addresses? The email addresses we store in CAS aren't always validated by us before we store them in our CAS database. I read about the need for a special parameter when this is the case:

<https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045>

> warning Discourse uses emails to map external users to Discourse users, and
> assumes that external emails are secure. IF YOU DO NOT VALIDATE EMAIL
> ADDRESSES BEFORE SENDING THEM TO DISCOURSE, YOUR SITE WILL BE EXTREMELY
> VULNERABLE!
> 
> Alternatively, if you insist on sending unvalidated emails BE SURE to set
> require_activation=true, this will force all emails to be validated by
> Discourse.

**Comment by eriko** [comment]
It does no validation as cas is assumed to be a source of truth.

**Comment by sudoman** [comment]
Just for the sake of anyone who wants to use `discourse_cas_sso` without validated emails, we're using this patch and it seems to be working correctly. If you want to use it, you need to test the code to make sure that it works properly. I'm releasing this patch under the same license as the `discourse_cas_sso`.

````
diff --git a/app/controllers/login_controller.rb b/app/controllers/login_controller.rb
index 197a1f7..656934a 100644
--- a/app/controllers/login_controller.rb
+++ b/app/controllers/login_controller.rb
@@ -26,6 +26,11 @@ class LoginController < ApplicationController
     sso.sso_secret = configatron.sso.secret
     sso.sso_url = sso.return_sso_url
 
+    # to avoid account hijacking via unverified email addresses:
+    # https://meta.discourse.org/t/official-single-sign-on-for-discourse-sso/13045
+    # -- sudoman 2018-08-31
+    sso.require_activation = true
+
     if configatron.custom_field.username
       sso.custom_fields["orig_username"] = username
     end
diff --git a/lib/single_sign_on.rb b/lib/single_sign_on.rb
index 8e782f8..79fe993 100644
--- a/lib/single_sign_on.rb
+++ b/lib/single_sign_on.rb
@@ -1,6 +1,6 @@
 class SingleSignOn
   ACCESSORS = [:nonce, :name, :username, :email, :avatar_url, :avatar_force_update,
-               :about_me, :external_id, :return_sso_url, :admin, :moderator, :suppress_welcome_message]
+               :about_me, :external_id, :return_sso_url, :admin, :moderator, :suppress_welcome_message, :require_activation]
   FIXNUMS = []
   BOOLS = [:avatar_force_update, :admin, :moderator, :suppress_welcome_message]
   NONCE_EXPIRY_TIME = 10.minutes
````

**Comment by eriko** [comment]
If you change that to be value read  from the config file I will merge it.
