### ISSUE TITLE
where should I provide the callback URL?

### ISSUE THREAD

**Issue by ikbear** [eriko/discourse_cas_sso#2]
Hi, I got this problem while running this app as a proxy:

```
no implicit conversion of nil into String
```

I don't know where should i provide the callback Url, could you provide a detailed readme.md? Thanks.

**Comment by eriko** [comment]
The callback url is automatically extracted from that data that discourse sends to cas_sso. This happens in the call to sso.return_sso_url

Is there any chance you can tell me what line that error is happening on?

**Comment by eriko** [comment]
The setup information on the front page is the documentation.

**Comment by ikbear** [comment]
I changed omniauth.rb here:

```url: 'https://cas.qiniu.io:9443'```

After logged in here on my CAS server: https://cas.qiniu.io:9443/login

I got this problem:

![screen shot 2015-06-21 at 09 44 47](https://cloud.githubusercontent.com/assets/232018/8270025/6d38c0e6-17fa-11e5-94a2-571ec471f131.png)

**Comment by ikbear** [comment]
In the method `sign`, the paramater of `payload` is `nil`.

**Comment by ikbear** [comment]
The detailed errors are:

```
Started GET "/auth/cas" for 127.0.0.1 at 2015-06-21 10:44:20 +0800
I, [2015-06-21T10:44:20.771559 #71656]  INFO -- omniauth: (cas) Request phase initiated.


Started GET "/auth/cas/callback?url&ticket=ST-1434854669rzz0YnEdznpPAHo2d09" for 127.0.0.1 at 2015-06-21 10:44:29 +0800
I, [2015-06-21T10:44:29.545835 #71656]  INFO -- omniauth: (cas) Callback phase initiated.
Processing by LoginController#create as HTML
  Parameters: {"url"=>nil, "ticket"=>"ST-1434854669rzz0YnEdznpPAHo2d09", "provider"=>"cas"}
Completed 500 Internal Server Error in 3ms

TypeError - no implicit conversion of nil into String:
   () Users/ikbear/Code/discourse_cas_sso/lib/single_sign_on.rb:67:in `sign'
   () Users/ikbear/Code/discourse_cas_sso/lib/single_sign_on.rb:24:in `parse'
   () Users/ikbear/Code/discourse_cas_sso/app/controllers/login_controller.rb:19:in `create'
```

**Comment by eriko** [comment]
Interesting.  I do all my development work is with pow so I do not access anything with port numbers.  I think that when I started working on this I did have discourse running on port 3000 but the url in the payload did not have a port.  Here is what I would suggest to test things

#1 make sure the configatron.sso.secret is set to the same thing in discourse

#2  try setting up pow or passenger so the you can access the apps via hostnames as I think it makes a difference with discourse.

#3 change 
```def login
    cookies.delete :query_string
    cookies.signed[:query_string] = request.query_string
    redirect_to signin_path :cas
  end
```

to 
```def login
    cookies.delete :query_string
    cookies.signed[:query_string] = request.query_string
    sso = SingleSignOn.parse(cookies.signed[:query_string], configatron.sso.secret)
    logger.info sso
    redirect_to signin_path :cas
  end

```

and see what is in the sso object.

**Comment by ikbear** [comment]
Where is the logger info stores?

It's same here after change it to pow:

![screen shot 2015-06-21 at 11 24 15](https://cloud.githubusercontent.com/assets/232018/8270230/488c4b10-1808-11e5-97ff-d6ad08643306.png)

the sso secret is the default.

![screen shot 2015-06-21 at 11 24 27](https://cloud.githubusercontent.com/assets/232018/8270232/52334646-1808-11e5-9c34-3d6126915c11.png)

**Comment by eriko** [comment]
the built in rails logger outputs to /log/development.log  


Discourse is running in pow also?

**Comment by ikbear** [comment]
when Discourse is running in pow, after CAS login, it redirect me to this url:

![screen shot 2015-06-21 at 11 34 07](https://cloud.githubusercontent.com/assets/232018/8270254/9425ec2e-1809-11e5-9612-c1550b6c9548.png)

Where should I change this discourse setting?

**Comment by ikbear** [comment]
It should not redirect back to `http://localhost:3000` but `http://sso.dev`

![screen shot 2015-06-21 at 11 41 31](https://cloud.githubusercontent.com/assets/232018/8270272/9d637f9e-180a-11e5-9932-be63b0d5256d.png)

**Comment by eriko** [comment]
But since it is failing at this point nothing will log.  

Ok what you just posted is interesting as it looks like the right thing almost happened.  Discourse sent you to cas_sso then you got bounced to cas then back to cas_sso.  At this point it sent you back to what it thought was the discourse server but with the wrong url.  Over in discourse there is a setting 
```# hostname running the forum
hostname = "www.example.com"
``` 
it maybe that discourse is senting the wrong url.

I would try adding 
```logger.info "sso return url #{sso.sso_url = sso.return_sso_url}"  
```
to that login function and see what discourse is sending you.

You can click on the stack on the left and move back to the context of LoginController#login and poke around.  My bet is that something will look odd.

I am home for the weekend and do not have access to my development environment so there is not much I can test with.

**Comment by ikbear** [comment]
I changed my hostname in discourse_default.conf:

![hostname](https://cloud.githubusercontent.com/assets/232018/8270346/ff8b8eec-180e-11e5-8eb1-2115720e69a3.png)

But the result is the same:

![sso-return-url](https://cloud.githubusercontent.com/assets/232018/8270347/07d3957c-180f-11e5-85b8-2262a6b2a2ad.png)

**Comment by eriko** [comment]
Did you restart discourse?

**Comment by ikbear** [comment]
Yes I use this command to restart discourse: touch tmp/restart.txt

ref: http://pow.cx/manual.html#section_2.5

**Comment by ikbear** [comment]
And I even restart pow with `touch .pow/restart.txt` and my computer.

**Comment by ikbear** [comment]
Maybe `discourse_defaults.conf` is for nginx, not for pow?

**Comment by eriko** [comment]
Interesting.  I would suggest that you ask on meta about what controls the return_url sent by sso as that seems to be the issue at this point.

discourse_defaults.conf should effect everything

**Comment by ikbear** [comment]
Thanks very much for your help. I am asking here: https://meta.discourse.org/t/what-controls-the-return-url-sent-by-sso/30268

**Comment by ikbear** [comment]
Hi there raising this error:

SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed

![screen shot 2015-06-28 at 10 51 25](https://cloud.githubusercontent.com/assets/232018/8394960/decd5b5c-1d83-11e5-849f-f016265b659e.png)

I use rubycas-server-demo.pem for CAS server's https

**Comment by eriko** [comment]
You need a real certificate when you are running in production.  You can add
   disable_ssl_verification: true
to config/initializers/omniauth.rb to disable validation.

**Comment by eriko** [comment]
I am closing this as it is different issue that what you started with.

**Comment by deargle** [comment]
I'm having a similar problem -- the sent url is blank.

The full attempted URL is this: https://discourse-cas.byu.edu/auth/cas/callback?url&ticket=ST-360671-fWeXcaVD00zZHwK3cBXl-smaug3

```
Started GET "/auth/cas/callback?url&ticket=ST-360671-fWeXcaVD00zZHwK3cBXl-smaug3" for 96.236.226.85 at 2016-07-28 13:34:47 -0600
I, [2016-07-28T13:34:47.971372 #347]  INFO -- omniauth: (cas) Callback phase initiated.

NoMethodError (undefined method `merge' for nil:NilClass):
  omniauth-cas (1.1.0) lib/omniauth/strategies/cas.rb:194:in `fetch_raw_info'
  omniauth-cas (1.1.0) lib/omniauth/strategies/cas.rb:84:in `callback_phase'
  omniauth (1.2.2) lib/omniauth/strategy.rb:227:in `callback_call'
  omniauth (1.2.2) lib/omniauth/strategy.rb:184:in `call!'
  omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
  omniauth (1.2.2) lib/omniauth/builder.rb:59:in `call'
  rack (1.5.2) lib/rack/etag.rb:23:in `call'
  rack (1.5.2) lib/rack/conditionalget.rb:25:in `call'
  rack (1.5.2) lib/rack/head.rb:11:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/flash.rb:254:in `call'
  rack (1.5.2) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.5.2) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.1.8) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.1.8) lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
  activerecord (4.1.8) lib/active_record/migration.rb:380:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.1.8) lib/active_support/callbacks.rb:82:in `run_callbacks'
  actionpack (4.1.8) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
  better_errors (2.0.0) lib/better_errors/middleware.rb:59:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.1.8) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.1.8) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.1.8) lib/rails/rack/logger.rb:20:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.5.2) lib/rack/methodoverride.rb:21:in `call'
  rack (1.5.2) lib/rack/runtime.rb:17:in `call'
  activesupport (4.1.8) lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  actionpack (4.1.8) lib/action_dispatch/middleware/static.rb:84:in `call'
  rack (1.5.2) lib/rack/sendfile.rb:112:in `call'
  railties (4.1.8) lib/rails/engine.rb:514:in `call'
  railties (4.1.8) lib/rails/application.rb:144:in `call'
  rack (1.5.2) lib/rack/lock.rb:17:in `call'
  rack (1.5.2) lib/rack/content_length.rb:14:in `call'
  rack (1.5.2) lib/rack/handler/webrick.rb:60:in `service'
  /home/deargle/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
  /home/deargle/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
  /home/deargle/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

```

**Comment by deargle** [comment]
And here's the output when I add the loggin functions to `def login` like you had @ikbear do:

I notice that the two urls are not https even though everything else is https-enabled and -redirected via nginx.

```
Started GET "/?sso=bm9uY2U9MmIxZWUxMGMyOTU4MjY2Y2Q4ZmM3NzVkOGZhN2NjYzMmcmV0dXJu%0AX3Nzb191cmw9aHR0cCUzQSUyRiUyRmlzbGFuZC1kZXYuYnl1LmVkdSUyRnNl%0Ac3Npb24lMkZzc29fbG9naW4%3D%0A&sig=a4d6a81f2ff56367b929f905564f9cb0e2696b0ed08180a6cb77de1fb817b74e" for 96.236.226.85 at 2016-07-28 14:05:33 -0600
Processing by LoginController#login as HTML
  Parameters: {"sso"=>"bm9uY2U9MmIxZWUxMGMyOTU4MjY2Y2Q4ZmM3NzVkOGZhN2NjYzMmcmV0dXJu\nX3Nzb191cmw9aHR0cCUzQSUyRiUyRmlzbGFuZC1kZXYuYnl1LmVkdSUyRnNl\nc3Npb24lMkZzc29fbG9naW4=\n", "sig"=>"a4d6a81f2ff56367b929f905564f9cb0e2696b0ed08180a6cb77de1fb817b74e"}
#<SingleSignOn:0x007f58286fefa0>
sso return url http://island-dev.byu.edu/session/sso_login
Redirected to http://discourse-cas.byu.edu/auth/cas
Completed 302 Found in 19ms (ActiveRecord: 0.0ms)
``

**Comment by eriko** [comment]
Based on the second comment you should check to make sure that `force https` is set in the discourse settings.

I wrote the is based on the first post

A couple questions.  
You have enabled SSO in discourse and set the sso url and sso secret up right?

The url you posted is is the one that discourse is redirecting you to either automatically or when you click a login link?  This is not the link that is bouncing you back to the discourse-cas from cas.byu.edu right ?

Just as a sidenote if you are using a current version of JasigCAS to provide your auth it is possible to configure it to provided SAML service and use that as long are you are not doing mulitsite instances. https://meta.discourse.org/t/saml-plugin-in-repo-multisite/38755

**Comment by deargle** [comment]
Okay, I just turned on `force https` and that gave me this: so now the return is https but initial outgoing is not.

Started GET "/?sso=bm9uY2U9MmIwYzgxZGNkNzJkNTViMjFiNWQyOWIwMzZmZGM1NjkmcmV0dXJu%0AX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZpc2xhbmQtZGV2LmJ5dS5lZHUlMkZz%0AZXNzaW9uJTJGc3NvX2xvZ2lu%0A&sig=281a124d173bce807a35ccae374f5c9e80cc3ecda4f624262130e03d3bdc9309" for 96.236.226.85 at 2016-07-28 14:21:28 -0600
Processing by LoginController#login as HTML
  Parameters: {"sso"=>"bm9uY2U9MmIwYzgxZGNkNzJkNTViMjFiNWQyOWIwMzZmZGM1NjkmcmV0dXJu\nX3Nzb191cmw9aHR0cHMlM0ElMkYlMkZpc2xhbmQtZGV2LmJ5dS5lZHUlMkZz\nZXNzaW9uJTJGc3NvX2xvZ2lu\n", "sig"=>"281a124d173bce807a35ccae374f5c9e80cc3ecda4f624262130e03d3bdc9309"}
#<SingleSignOn:0x0000000374b0a0>
sso return url https://island-dev.byu.edu/session/sso_login
Redirected to http://discourse-cas.byu.edu/auth/cas
Completed 302 Found in 1ms (ActiveRecord: 0.0ms)

> You have enabled SSO in discourse and set the sso url and sso secret up right?

Yes, below are the settings I have (and the secret matches): 

![image](https://cloud.githubusercontent.com/assets/1174653/17228178/f2804f76-54df-11e6-9ab3-d002fcfcfdff.png)

> This is not the link that is bouncing you back to the discourse-cas from cas.byu.edu right ?

Actually, this _is_ where I'm being sent after authenticating at cas.byu.edu.

**Comment by deargle** [comment]
> Just as a sidenote if you are using a current version of JasigCAS to provide your auth it is possible to configure it to provided SAML service and use that as long are you are not doing mulitsite instances. https://meta.discourse.org/t/saml-plugin-in-repo-multisite/38755

Thanks, but I tried and I haven't found documentation for cas.byu.edu saml yet... this is a better solution anyways because I want cas to be the _only_ auth method.

**Comment by eriko** [comment]
I am thinking about this but as to saml you can turn off all the other auth methods and just leave saml.  That said let me think about your problem.

**Comment by deargle** [comment]
> The url you posted is is the one that discourse is redirecting you to either automatically or when you click a login link? This is not the link that is bouncing you back to the discourse-cas from cas.byu.edu right ?

Just to be perfectly clear, I start in discourse by clicking the "login link." I then end up on cas.byu.edu, I authenticate, then I get bounced back to https://discourse-cas.byu.edu/auth/cas/callback?url&ticket=<ticket>

**Comment by eriko** [comment]
The sequence should look something like:
discourse -> discourse-cas -> cas -> discourse-cas -> discourse 

I think somewhere you said discourse-cas is running behind nginx based on that here is my theory. Since you have discourse-cas running behind nginx (where nginx is doing the ssl work) discourse-cas does not know to send along https urls and just sends http ones. So discourse-cas sends a http url to cas and then you can not get back to discourse-cas.  It looks like you can set nginx to tell rails to send https with `proxy_set_header X-Forwarded-Proto https;`https://stackoverflow.com/questions/10432266/https-redirect-for-rails-app-behind-proxy

**Comment by deargle** [comment]
Progress with `proxy_set_header X-Forwarded-Proto https;`! Closer...

Now I bounce back to https://discourse-cas.byu.edu/auth/cas/callback?url=https%3A%2F%2Fisland-dev.byu.edu%2F&ticket=<ticket>

And I get the same "undefine method `merge' for nil:NilClass stacktrace as above.

Isn't it supposed to return to /session/sso_login? I might have to manually add that since https may be making it impossible to read the full url. Tips on where-to?

**Comment by deargle** [comment]
No, manually adding /session/sso_login doesn't fix that error... I'll see what other parameter is missing.

**Comment by deargle** [comment]
Sorry, that previous url _does_ have a ticket parameter, I just formatted it incorrectly.

**Comment by eriko** [comment]
Hmm ok do you know if cas-byu is set up to do anything odd?  Like return the uid as something other than `user` I am looking at the the code around where the merge error is and I wonder if something is non standard.

From omnauth-cas "uid_field - The user data attribute to use as your user's unique identifier. Defaults to 'user' (which usually contains the user's login name)."

You can dump out everything being returned by cas with
`logger.info request.env["omniauth.auth"] `

**Comment by eriko** [comment]
The following is for clarities sake as there is a stack of redirects going on here.
island-dev (sends return to island-dev) -> 
discourse-cas (sends return to discourse-cas) -> 
cas (uses return to discourse-cas)-> 
discourse-cas (uses return to inland-dev that was stored by the login method) -> 
island-dev

**Comment by deargle** [comment]
> You can dump out everything being returned by cas with
logger.info request.env["omniauth.auth"]

Excuse my rails noob question but where would I put that? I don't think I'm reaching the `create` method.

> Hmm ok do you know if cas-byu is set up to do anything odd? Like return the uid as something other than user I am looking at the the code around where the merge error is and I wonder if something is non standard.

Yes, they _do_ do odd things. I thought I accounted for that in the config:

```
configatron.cas.email_attribute = 'emailAddress'    # CAS attribute containing user's e-mail. Example: 'UserPrincipalName'
configatron.cas.name_attribute = 'netId' # CAS attribute containing user's username. Example: 'Name'

configatron.cas.attributes_hash = :extra #in some small about a of cases this may be :info
```

Here's what I see when I dump from `fetch_raw_info` around here: 

```
def fetch_raw_info(ticket)
       
        ticket_user_info = validate_service_ticket(ticket).user_info
        p validate_service_ticket(ticket)
       
        custom_user_info = options.fetch_raw_info.call(self, options, ticket, ticket_user_info)
        self.raw_info = ticket_user_info.merge(custom_user_info)
      end
```

```
<OmniAuth::Strategies::CAS::ServiceTicketValidator:0x007f4788a41920 @options=#<OmniAuth::Strategy::Options email_key="email" fetch_raw_info=#<Proc:0x00000002cbf0a0@/home/deargle/.rvm/gems/ruby-2.3.1/gems/omniauth-cas-1.1.0/lib/omniauth/strategies/cas.rb:37> first_name_key="first_name" host="cas.byu.edu" image_key="image" last_name_key="last_name" location_key="location" login_url="/login" logout_url="/logout" name=:cas name_key="name" nickname_key="user" on_single_sign_out=#<Proc:0x00000002cbf118@/home/deargle/.rvm/gems/ruby-2.3.1/gems/omniauth-cas-1.1.0/lib/omniauth/strategies/cas.rb:28> path="/cas/login" phone_key="phone" port=nil service_validate_url="/serviceValidate" setup=false skip_info=false ssl=true uid_field="user">, @uri=#<URI::HTTPS https://cas.byu.edu/cas/login/serviceValidate?service=https%3A%2F%2Fdiscourse-cas.byu.edu%2Fauth%2Fcas%2Fcallback%3Furl%3Dhttps%253A%252F%252Fisland-dev.byu.edu%252Fsession%252Fsso_login&ticket=ST-358549-DxdaLb4ZP3Mlo0dzRMxJ-smaug4>, @response_body="", @success_body=nil>

```

I don't know if that's helpful, maybe that's just what omniauth-cas _thinks_ it should be. 

I'm going to have to come back to this in a few hours...

**Comment by deargle** [comment]
`ticket_user_info` is `nil` in the above if I `p` that...

**Comment by deargle** [comment]
wait a minute, `@response_body` is empty, does that mean it didn't validate? odd if so...

**Comment by eriko** [comment]
One horrible thing to keep in mind is that omniauth-cas is a bit crappy.  Somehere on my list is to rewrite this all using rack-cas with is much cleaner and currently maintained unlike omniauth-cas.  

You might need to set that netid setting in config/initializer/omniauth.rb  which is the provider for the trip to and from cas.

**Comment by eriko** [comment]
Oh and if you are not making back to create dumping out the cas stuff would not work. I will see if I can think of another way to get at it.

**Comment by eriko** [comment]
Hmm it might be that you need to set
uid_key to netid in in the omniauth config.
uid_key - The user ID data attribute to use as your user's unique identifier. Defaults to 'user' (which usually contains the user's login name).

**Comment by deargle** [comment]
Ah ha! I had made a mistake in setting the omniauth cas url. I had written this:

` https://cas.byu.edu/cas/login`

Instead of:
`https://cas.byu.edu/cas`

So it was trying to validate at:

`https://cas.byu.edu/cas/login/serviceValidate`

Which of course is wrong. I didn't need to set uid_key in initializers/omniauth.rb, just setting it in config/configatron/defaults.rb was sufficient. Only the login controller needed to know the right key, and it pulls from that config, not omniauth's config.

For the sake of completeness, I went back and undid the things I changed earlier, to see which were important. The answer: none of them (??).

I didn't need to have `force https` on, I just tested without and my nginx redirects are sufficient. 

`proxy_set_header X-Forwarded-Proto https;` wasn't even necessary. I guess my http => https redirects and my forward and reverse proxy headers in there are sufficient.

This means that at the most basic, this is what a successful route log looked like. Note that the `url` parameter is blank!

```
Started GET "/auth/cas" for 96.236.226.85 at 2016-07-28 18:38:18 -0600
I, [2016-07-28T18:38:18.555600 #47452]  INFO -- omniauth: (cas) Request phase initiated.


Started GET "/auth/cas/callback?url&ticket=ST-365658-ebpIaSGEjuc6c4resd3A-smaug4" for 96.236.226.85 at 2016-07-28 18:38:23 -0600
I, [2016-07-28T18:38:23.175580 #47452]  INFO -- omniauth: (cas) Callback phase initiated.
Processing by LoginController#create as HTML
  Parameters: {"url"=>nil, "ticket"=>"ST-365658-ebpIaSGEjuc6c4resd3A-smaug4", "provider"=>"cas"}
allowed_groups true && !denied_groups true
Redirected to http://island-dev.byu.edu/session/sso_login?sso=bm9uY2U9ZTgwM2UyODZkNzM1NWUyZDNjMDM4YmFhMzZlYzY4YTgmbmFtZT1k%0AZWFyZ2xlJnVzZXJuYW1lPWRlYXJnbGUmZXh0ZXJuYWxfaWQ9ZGVhcmdsZSZy%0AZXR1cm5fc3NvX3VybD1odHRwJTNBJTJGJTJGaXNsYW5kLWRldi5ieXUuZWR1%0AJTJGc2Vzc2lvbiUyRnNzb19sb2dpbg%3D%3D%0A&sig=f83660b80118af8448857b5508fa33d1abd315aa2e12770e3bf3ea686192128a
Completed 302 Found in 2ms (ActiveRecord: 0.0ms)
```

Thanks for your help debugging! I would have still been pulling my hair out on the earlier things.

**Comment by deargle** [comment]
Just kidding. proxy_set_header X-Forwarded-Proto https; _was__ necessary. Something something caching, faulty test.

Thanks again!

**Comment by eriko** [comment]
I am glad you got it working.  One of my co workers spent some time last week talking to another school that is thinking about using discourse for a campus community.  His takeaway was that the once it is set up the hard work is maintaining and curating the community.

**Comment by deargle** [comment]
Yeah, hopefully our implementation will be more manageable since it's just targeted for current students and alumni from one department. Curating one for the whole school would be... unpleasant.

**Comment by eriko** [comment]
How do you plan on handling accounts for alumni.  This is an issue that we have not resolved.

**Comment by deargle** [comment]
Our alumni still have the same CAS accounts they had as students, so it's
not an issue for us. We can treat them the same as current students.
