### ISSUE TITLE
Potential solution to integrating single log out

### ISSUE THREAD

**Issue by ramanbuttar** [eriko/discourse_cas_sso#5]
Go to `Settings` -> `Users`
Change `logout_redirect` to https://sso.example.com/logout?service=http://discourse.example.com

When a user clicks on Log Out, first the local Discourse session will be destroyed. Then the user will be redirected to the provided URL, which will destroy the SSO session, and the user will once again be redirected to Discourse to show the final landing page.

**Comment by eriko** [comment]
I have been doing this, with out the service and that is a nice touch.  What this does not handle is the SLO signals that the CAS server sends out when the user session expires on the CAS server.

I will add out idea to the docs for the app.
