### ISSUE TITLE
readme links aren't links

### ISSUE THREAD

**Issue by deargle** [eriko/discourse_cas_sso#6]
> * Functioning CAS server that returns username and email address
> * CAS server is using SSL (for testing you can disable this see [here][1])
> * Read through the first post of [this][2] the Official Single-Sign-On for Discourse

[1] should be ?
[2] should be https://meta.discourse.org/t/official-single-sign-on-for-discourse/13045

**Comment by eriko** [comment]
Seems good.  I found the first one and changed the other one.

I am about to go on vacation at the end of the week so if you have an questions ask then sooner rather than later.
