### ISSUE TITLE
undefined method `suppress_welcome_message='

### ISSUE THREAD

**Issue by nozpheratu** [eriko/discourse_cas_sso#8]
https://github.com/eriko/discourse_cas_sso/blob/master/app/controllers/login_controller.rb#L23 is giving a `NoMethodError`.

**Comment by eriko** [comment]
Make sure your config file has a line in it like this one.
configatron.sso.suppress_welcome_message = false
https://github.com/eriko/discourse_cas_sso/blob/master/config/configatron/defaults.rb#L14

**Comment by nozpheratu** [comment]
@eriko Yep, it's there.

**Comment by eriko** [comment]
Honestly you can nuke
https://github.com/eriko/discourse_cas_sso/blob/master/app/controllers/login_controller.rb#L23
for now.  it deals with an edge case that I have quite figured out what causes it.  

Also I have a couple small warnings about cas and also this app.  The first is that unless you are working in an environment that already uses cas for auth you might want to avoid it it.  There is a first class SAML plugin (no app needed) that discourse wrote.  The second part is that when I have time time and we (at work) have fully switched over to office365 I will switch to using SAML and abandon this app.

**Comment by nozpheratu** [comment]
@eriko Thanks for the warning. We have an existing CAS setup, and this seems to work for us so far so we'll probably just keep at it for now.

**Comment by eriko** [comment]
Sounds good.
