### ISSUE TITLE
Dangling symlink cases rebuild failure

### ISSUE THREAD

**Issue by sudoman** [eriko/discourse_cas_sso#9]
This is a new type of issue brought about by a change in Discourse, but it seems like the `public/cas_sso -> /Users/eriko/.pow/cas_sso` symlink doesn't belong in this repository.

<https://meta.discourse.org/t/find-chown-command-in-discourse-rebuild-step-fails-when-there-are-dangling-symlinks/95860>

**Comment by eriko** [comment]
You are correct and it has been removed.
